### ISSUE TITLE
Custom content types vs. "ArchivesSpace" entity bundles

### ISSUE THREAD

**Issue by jasloe** [jasloe/archivesspace-drupal#9]
@seth-shaw-unlv I take it we're designing around node bundles instead of custom entities? Do you have a preference or rationale either way? Getting started on the Accessions config and want to make sure we're on the same page!

**Comment by seth-shaw-unlv** [comment]
I don't have any rationale other than familiarity. If you think a custom entity would work better I'm okay with that. I'll just need to see how you would change what I've done so far so I can reorient myself.

**Comment by jasloe** [comment]
@seth-shaw-unlv I just pushed something super simple to the custom-bundles branch. Only took a couple of hours to untangle the documentation (and a little help from configuration exports). Working with custom content entities is pretty interesting. I like how everything is segmented, kept out of core content tables (for the most part). No unnecessary node overhead. Seems to work ok with Views and Search API Solr. Totally willing to pursue this if you agree it's a good idea. But I haven't made my case very well other than, well, it's interesting.

**Comment by seth-shaw-unlv** [comment]
I'm hesitant. From what I understand this method would remove some of the possibly useful node features such as the publish flag, stickiness, user comments, dates created and last updated.

This would also require us to create a digital object bundle of the archivesspace entity type if we wanted them to show up in a view along-side other archivesspace objects (since a view can't display items from differing entity types, e.g. you can have a view showing users and content together as results because they are different entity types). I think I would rather have archivesspace node bundles so that a view can show both them and other content types (e.g. Islandora digital objects) in a single view.

**Comment by jasloe** [comment]
That's fine. Just exploring options. The branch does incorporate the publish flag, dates created, and last updated date. Stickiness is hardwired to node would have to be extended from that class (or just roll my own). Comments can target any entity type. 

I suppose the Views issue you raise is a major show stopper for us and one I hadn't realized. As such, I'll pocket the branch for posterity. 

I'll plan on following the established node pattern for accessions and figure out the migrate_plus authentication plugin next week.
